using MediatR;
using System.Linq.Expressions;
using FluentValidation.Results;
using LazyCrud.Core.Domain.Aggregates.CommonAgg.Queries;
namespace LazyCrud.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Queries.Models
{
	using Filters;
    using Entities;
	public partial class SystemPanelSubItemQueryModel : BaseQueryModel<SystemPanelSubItem> {
        public override Expression<Func<SystemPanelSubItem, bool>> GetFilter() => SystemPanelSubItemFilters.GetFilters(this, IsOrSpecification==true);
		public int? SystemPanelSubItemIdEqual { get; set; }
		public int? SystemPanelSubItemIdNotEqual { get; set; }
		public int[]? SystemPanelSubItemIdContains { get; set; }
		public int[]? SystemPanelSubItemIdNotContains { get; set; }
		public int? SystemPanelSubItemIdSince { get; set; }
		public int? SystemPanelSubItemIdUntil { get; set; }
		public int? SystemPanelSubItemIdLessThan { get; set; }
		public int? SystemPanelSubItemIdGreaterThan { get; set; }
		public int? SystemPanelSubItemIdLessThanOrEqual { get; set; }
		public int? SystemPanelSubItemIdGreaterThanOrEqual { get; set; }
		public int? SystemPanelIdEqual { get; set; }
		public int? SystemPanelIdNotEqual { get; set; }
		public int[]? SystemPanelIdContains { get; set; }
		public int[]? SystemPanelIdNotContains { get; set; }
		public int? SystemPanelIdSince { get; set; }
		public int? SystemPanelIdUntil { get; set; }
		public int? SystemPanelIdLessThan { get; set; }
		public int? SystemPanelIdGreaterThan { get; set; }
		public int? SystemPanelIdLessThanOrEqual { get; set; }
		public int? SystemPanelIdGreaterThanOrEqual { get; set; }
		public bool? IsSubItemEqual { get; set; }
		public string? IconEqual { get; set; }
		public string? IconNotEqual { get; set; }
		public string? IconContains { get; set; }
		public string? IconStartsWith { get; set; }
		public string? DescriptionEqual { get; set; }
		public string? DescriptionNotEqual { get; set; }
		public string? DescriptionContains { get; set; }
		public string? DescriptionStartsWith { get; set; }
		public string? UrlEqual { get; set; }
		public string? UrlNotEqual { get; set; }
		public string? UrlContains { get; set; }
		public string? UrlStartsWith { get; set; }
		public bool? LinkDiretoEqual { get; set; }
		public bool? ActionButtonEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class SystemPanelQueryModel : BaseQueryModel<SystemPanel> {
        public override Expression<Func<SystemPanel, bool>> GetFilter() => SystemPanelFilters.GetFilters(this, IsOrSpecification==true);
		public string? IconEqual { get; set; }
		public string? IconNotEqual { get; set; }
		public string? IconContains { get; set; }
		public string? IconStartsWith { get; set; }
		public string? DescriptionEqual { get; set; }
		public string? DescriptionNotEqual { get; set; }
		public string? DescriptionContains { get; set; }
		public string? DescriptionStartsWith { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class SystemPanelGroupQueryModel : BaseQueryModel<SystemPanelGroup> {
        public override Expression<Func<SystemPanelGroup, bool>> GetFilter() => SystemPanelGroupFilters.GetFilters(this, IsOrSpecification==true);
		public string? IconEqual { get; set; }
		public string? IconNotEqual { get; set; }
		public string? IconContains { get; set; }
		public string? IconStartsWith { get; set; }
		public string? DescriptionEqual { get; set; }
		public string? DescriptionNotEqual { get; set; }
		public string? DescriptionContains { get; set; }
		public string? DescriptionStartsWith { get; set; }
		public string? CodeEqual { get; set; }
		public string? CodeNotEqual { get; set; }
		public string? CodeContains { get; set; }
		public string? CodeStartsWith { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class CargaTabelaQueryModel : BaseQueryModel<CargaTabela> {
        public override Expression<Func<CargaTabela, bool>> GetFilter() => CargaTabelaFilters.GetFilters(this, IsOrSpecification==true);
		public string? TableNameEqual { get; set; }
		public string? TableNameNotEqual { get; set; }
		public string? TableNameContains { get; set; }
		public string? TableNameStartsWith { get; set; }
		public string? FilePathEqual { get; set; }
		public string? FilePathNotEqual { get; set; }
		public string? FilePathContains { get; set; }
		public string? FilePathStartsWith { get; set; }
		public bool? IsInitializedEqual { get; set; }
		public int? TotalEqual { get; set; }
		public int? TotalNotEqual { get; set; }
		public int[]? TotalContains { get; set; }
		public int[]? TotalNotContains { get; set; }
		public int? TotalSince { get; set; }
		public int? TotalUntil { get; set; }
		public int? TotalLessThan { get; set; }
		public int? TotalGreaterThan { get; set; }
		public int? TotalLessThanOrEqual { get; set; }
		public int? TotalGreaterThanOrEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class SystemSettingsAggSettingsQueryModel : BaseQueryModel<SystemSettingsAggSettings> {
        public override Expression<Func<SystemSettingsAggSettings, bool>> GetFilter() => SystemSettingsAggSettingsFilters.GetFilters(this, IsOrSpecification==true);
		public bool? AutoSaveSettingsEnabledEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
