using Lazy.Crud.Core.Application.DTO.Attributes;

namespace Lazy.Crud.Core.Application.DTO.Attributes
{
    /// <summary>
    /// Automatically generates default files for the feature/entity.
    /// </summary>
    /// <category>Code Generation (T4)</category>
    public class AutoGenerateDefaultFiles : Attribute
    {
    }
}
