using Lazy.Crud.Core.Application.DTO.Attributes;

namespace Lazy.Crud.Core.Application.DTO.Attributes
{
    /// <summary>
    /// Automatically generates default data files (e.g., seeds/initial data) for the aggregate.
    /// </summary>
    [H1("Auto-generate Default Data Files")]
    [Category("Code Generation (T4)", "Automatically generate default data files (seeds/initial data).")]
    public class AutoGenerateDefaultDataFiles : Attribute
    {
    }
}
