using Niu.Nutri.Core.Application.DTO.Attributes;

namespace Niu.Nutri.Core.Application.DTO.Attributes
{
    /// <summary>
    /// Automatically generates default files for the feature/entity.
    /// </summary>
    [H1("Auto-generate Default Files")]
    [Category("Code Generation (T4)", "Automatically generate default files for the entity/feature.")]
    public class AutoGenerateDefaultFiles : Attribute
    {
    }
}
