using Lazy.Crud.Core.Application.DTO.Attributes;

namespace Lazy.Crud.Core.Application.DTO.Attributes
{
    /// <summary>
    /// Automatically generates default data files (e.g., seeds/initial data) for the aggregate.
    /// </summary>
    /// <category>Code Generation (T4)</category>
    public class AutoGenerateDefaultDataFiles : Attribute
    {
    }
}
