using MediatR;
using System.Linq.Expressions;
using FluentValidation.Results;
using LazyCrudBuilder.Core.Domain.Aggregates.CommonAgg.Queries;
namespace LazyCrudBuilder.Users.Domain.Aggregates.UsersAgg.Queries.Models
{
	using Filters;
    using Entities;
	public partial class UserProfileAccessQueryModel : BaseQueryModel<UserProfileAccess> {
        public override Expression<Func<UserProfileAccess, bool>> GetFilter() => UserProfileAccessFilters.GetFilters(this, IsOrSpecification==true);
		public string? DescriptionEqual { get; set; }
		public string? DescriptionNotEqual { get; set; }
		public string? DescriptionContains { get; set; }
		public string? DescriptionStartsWith { get; set; }
		public int? UserProfileIdEqual { get; set; }
		public int? UserProfileIdNotEqual { get; set; }
		public int[]? UserProfileIdContains { get; set; }
		public int[]? UserProfileIdNotContains { get; set; }
		public int? UserProfileIdSince { get; set; }
		public int? UserProfileIdUntil { get; set; }
		public int? UserProfileIdLessThan { get; set; }
		public int? UserProfileIdGreaterThan { get; set; }
		public int? UserProfileIdLessThanOrEqual { get; set; }
		public int? UserProfileIdGreaterThanOrEqual { get; set; }
		public int? SystemPanelSubItemIdEqual { get; set; }
		public int? SystemPanelSubItemIdNotEqual { get; set; }
		public int[]? SystemPanelSubItemIdContains { get; set; }
		public int[]? SystemPanelSubItemIdNotContains { get; set; }
		public int? SystemPanelSubItemIdSince { get; set; }
		public int? SystemPanelSubItemIdUntil { get; set; }
		public int? SystemPanelSubItemIdLessThan { get; set; }
		public int? SystemPanelSubItemIdGreaterThan { get; set; }
		public int? SystemPanelSubItemIdLessThanOrEqual { get; set; }
		public int? SystemPanelSubItemIdGreaterThanOrEqual { get; set; }
		public int? SystemPanelIdEqual { get; set; }
		public int? SystemPanelIdNotEqual { get; set; }
		public int[]? SystemPanelIdContains { get; set; }
		public int[]? SystemPanelIdNotContains { get; set; }
		public int? SystemPanelIdSince { get; set; }
		public int? SystemPanelIdUntil { get; set; }
		public int? SystemPanelIdLessThan { get; set; }
		public int? SystemPanelIdGreaterThan { get; set; }
		public int? SystemPanelIdLessThanOrEqual { get; set; }
		public int? SystemPanelIdGreaterThanOrEqual { get; set; }
		public int? SystemPanelGroupIdEqual { get; set; }
		public int? SystemPanelGroupIdNotEqual { get; set; }
		public int[]? SystemPanelGroupIdContains { get; set; }
		public int[]? SystemPanelGroupIdNotContains { get; set; }
		public int? SystemPanelGroupIdSince { get; set; }
		public int? SystemPanelGroupIdUntil { get; set; }
		public int? SystemPanelGroupIdLessThan { get; set; }
		public int? SystemPanelGroupIdGreaterThan { get; set; }
		public int? SystemPanelGroupIdLessThanOrEqual { get; set; }
		public int? SystemPanelGroupIdGreaterThanOrEqual { get; set; }
		public bool? IsSubItemEqual { get; set; }
		public int? ParentIdEqual { get; set; }
		public int? ParentIdNotEqual { get; set; }
		public int[]? ParentIdContains { get; set; }
		public int[]? ParentIdNotContains { get; set; }
		public int? ParentIdSince { get; set; }
		public int? ParentIdUntil { get; set; }
		public int? ParentIdLessThan { get; set; }
		public int? ParentIdGreaterThan { get; set; }
		public int? ParentIdLessThanOrEqual { get; set; }
		public int? ParentIdGreaterThanOrEqual { get; set; }
		public bool? IsDirectLinkEqual { get; set; }
		public bool? CanInsertEqual { get; set; }
		public bool? CanUpdateEqual { get; set; }
		public bool? CanListEqual { get; set; }
		public bool? CanDeleteEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class UserCurrentAccessSelectedQueryModel : BaseQueryModel<UserCurrentAccessSelected> {
        public override Expression<Func<UserCurrentAccessSelected, bool>> GetFilter() => UserCurrentAccessSelectedFilters.GetFilters(this, IsOrSpecification==true);
		public int? UserProfileIdEqual { get; set; }
		public int? UserProfileIdNotEqual { get; set; }
		public int[]? UserProfileIdContains { get; set; }
		public int[]? UserProfileIdNotContains { get; set; }
		public int? UserProfileIdSince { get; set; }
		public int? UserProfileIdUntil { get; set; }
		public int? UserProfileIdLessThan { get; set; }
		public int? UserProfileIdGreaterThan { get; set; }
		public int? UserProfileIdLessThanOrEqual { get; set; }
		public int? UserProfileIdGreaterThanOrEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class UserProfileListQueryModel : BaseQueryModel<UserProfileList> {
        public override Expression<Func<UserProfileList, bool>> GetFilter() => UserProfileListFilters.GetFilters(this, IsOrSpecification==true);
		public int? UserIdEqual { get; set; }
		public int? UserIdNotEqual { get; set; }
		public int[]? UserIdContains { get; set; }
		public int[]? UserIdNotContains { get; set; }
		public int? UserIdSince { get; set; }
		public int? UserIdUntil { get; set; }
		public int? UserIdLessThan { get; set; }
		public int? UserIdGreaterThan { get; set; }
		public int? UserIdLessThanOrEqual { get; set; }
		public int? UserIdGreaterThanOrEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class UserProfileQueryModel : BaseQueryModel<UserProfile> {
        public override Expression<Func<UserProfile, bool>> GetFilter() => UserProfileFilters.GetFilters(this, IsOrSpecification==true);
		public string? DescriptionEqual { get; set; }
		public string? DescriptionNotEqual { get; set; }
		public string? DescriptionContains { get; set; }
		public string? DescriptionStartsWith { get; set; }
		public string? CodeEqual { get; set; }
		public string? CodeNotEqual { get; set; }
		public string? CodeContains { get; set; }
		public string? CodeStartsWith { get; set; }
		public string? InitialPageEqual { get; set; }
		public string? InitialPageNotEqual { get; set; }
		public string? InitialPageContains { get; set; }
		public string? InitialPageStartsWith { get; set; }
		public bool? IsPrivateProfileEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class UsersAggSettingsQueryModel : BaseQueryModel<UsersAggSettings> {
        public override Expression<Func<UsersAggSettings, bool>> GetFilter() => UsersAggSettingsFilters.GetFilters(this, IsOrSpecification==true);
		public int? UserIdEqual { get; set; }
		public int? UserIdNotEqual { get; set; }
		public int[]? UserIdContains { get; set; }
		public int[]? UserIdNotContains { get; set; }
		public int? UserIdSince { get; set; }
		public int? UserIdUntil { get; set; }
		public int? UserIdLessThan { get; set; }
		public int? UserIdGreaterThan { get; set; }
		public int? UserIdLessThanOrEqual { get; set; }
		public int? UserIdGreaterThanOrEqual { get; set; }
		public bool? AutoSaveSettingsEnabledEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class UserQueryModel : BaseQueryModel<User> {
        public override Expression<Func<User, bool>> GetFilter() => UserFilters.GetFilters(this, IsOrSpecification==true);
		public string? UserNameEqual { get; set; }
		public string? UserNameNotEqual { get; set; }
		public string? UserNameContains { get; set; }
		public string? UserNameStartsWith { get; set; }
		public string? NameEqual { get; set; }
		public string? NameNotEqual { get; set; }
		public string? NameContains { get; set; }
		public string? NameStartsWith { get; set; }
		public System.DateOnly? BirthDateEqual { get; set; }
		public System.DateOnly? BirthDateNotEqual { get; set; }
		public System.DateOnly[]? BirthDateContains { get; set; }
		public System.DateOnly[]? BirthDateNotContains { get; set; }
		public System.DateOnly? BirthDateSince { get; set; }
		public System.DateOnly? BirthDateUntil { get; set; }
		public System.DateOnly? BirthDateLessThan { get; set; }
		public System.DateOnly? BirthDateGreaterThan { get; set; }
		public System.DateOnly? BirthDateLessThanOrEqual { get; set; }
		public System.DateOnly? BirthDateGreaterThanOrEqual { get; set; }
		public LazyCrudBuilder.Users.Enumerations.GenderEnum? GenderEqual { get; set; }
		public bool? NeedResetPasswordEqual { get; set; }
		public bool? NeedSendOnboardingMailEqual { get; set; }
		public string? ProfilePictureEqual { get; set; }
		public string? ProfilePictureNotEqual { get; set; }
		public string? ProfilePictureContains { get; set; }
		public string? ProfilePictureStartsWith { get; set; }
		public bool? CanUpdatePasswordEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
