using LazyCrud.Core.Application.DTO.Attributes;
using LazyCrud.Core.Domain.Aggregates.CommonAgg.Entities;
using LazyCrud.Core.Domain.Attributes.T4;

namespace LazyCrud.Marketplace.Domain.Aggregates.UsersAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class Carrinho : Entity
    {
    
        public int IdUsuario { get; set; }
    
        public int IdProduto { get; set; }
    
    
        public string Modalidadefrete { get; set; }
    
        public double Total { get; set; }
    
        public string TipoPagamento { get; set; }
    }
}
