using LazyCrudBuilder.Core.Application.DTO.Attributes;
using LazyCrudBuilder.Core.Domain.Aggregates.CommonAgg.Entities;
using LazyCrudBuilder.Core.Domain.Attributes.T4;

namespace LazyCrudBuilder.MarketPlace.Domain.Aggregates.UsersAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class Categoriaproduto : Entity
    {
    
        public ImageFieldInfo Nome { get; set; }
    }
}
