using LazyCrudBuilder.Core.Application.DTO.Attributes;
using LazyCrudBuilder.Core.Domain.Aggregates.CommonAgg.Entities;
using LazyCrudBuilder.Core.Domain.Attributes.T4;

namespace LazyCrudBuilder.MarketPlace.Domain.Aggregates.UsersAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class Produto : Entity
    {
    
        public string Nome { get; set; }
    
        public int Estoque { get; set; }
    
        public int Preco { get; set; }
    
        public int CategoriaId { get; set; }
    }
}
