using LazyCrud.Core.Application.DTO.Attributes;
using LazyCrud.Core.Domain.Aggregates.CommonAgg.Entities;
using LazyCrud.Core.Domain.Attributes.T4;

namespace LazyCrud.Marketplace.Domain.Aggregates.UsersAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class Produto : ActivableEntity
    {
    
    
        public string Nome { get; set; }
    
        public int Estoque { get; set; }
    
        public double Preco { get; set; }
    
        public string Categoria { get; set; }
    
        public int IdCategoria { get; set; }
    }
}
