using Newtonsoft.Json;
using LazyCrudBuilder.Core.Application.DTO.Attributes;
using LazyCrudBuilder.Core.Domain.Aggregates.CommonAgg.Entities;
using LazyCrudBuilder.Core.Domain.Attributes.T4;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace LazyCrudBuilder.Users.Domain.Aggregates.UsersAgg.Entities
{
    [Steppable(2), EndpointsT4(EndpointTypes.HttpAll), DoNotReplaceAfterGenerated, AutoGenerateDefaultFiles]
    public class UserProfile : SteppableEntity
    {
        [Title, Step(1), DisplayOnList, DisplayName("Name do Perfil"), Required]
        public string? Description { get; set; }

        [Subtitle, Step(1), DisplayOnList, DisplayName("Code")]
        public string? Code { get; set; }

        [Step(2), DisplayOnList]
        public string? InitialPage { get; set; }

        [DisplayOnList, DisplayName("Private Profile?")]
        public bool IsPrivateProfile { get; set; }

        [ForeignDataSelectorDropDownWithAutoComplete]
        public List<UserProfileAccess> Accesses { get; set; } = new List<UserProfileAccess>();

        [IgnorePropertyT4]
        public List<UserProfileList> AccessesList { get; set; }

        //[IgnorePropertyT4]
        //public List<SystemPanelGroup> MenusGroup { get; set; }
    }
}
