using Saga.Core.Application.DTO.Attributes;
using Saga.Core.Domain.Aggregates.CommonAgg.Entities;
using Saga.Core.Domain.Attributes.T4;

namespace Saga.DefaultTemplate.Domain.Aggregates.UsersAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class DefaultEntity : Entity
    {
    }
}
