using MediatR;
using System.Linq.Expressions;
using FluentValidation.Results;
using LazyCrud.Core.Domain.Aggregates.CommonAgg.Queries;
namespace LazyCrud.MarketPlace.Domain.Aggregates.MarketPlaceAgg.Queries.Models
{
	using Filters;
    using Entities;
	public partial class ProdutoQueryModel : BaseQueryModel<Produto> {
        public override Expression<Func<Produto, bool>> GetFilter() => ProdutoFilters.GetFilters(this, IsOrSpecification==true);
		public string? NomeEqual { get; set; }
		public string? NomeNotEqual { get; set; }
		public string? NomeContains { get; set; }
		public string? NomeStartsWith { get; set; }
		public int? EstoqueEqual { get; set; }
		public int? EstoqueNotEqual { get; set; }
		public int[]? EstoqueContains { get; set; }
		public int[]? EstoqueNotContains { get; set; }
		public int? EstoqueSince { get; set; }
		public int? EstoqueUntil { get; set; }
		public int? EstoqueLessThan { get; set; }
		public int? EstoqueGreaterThan { get; set; }
		public int? EstoqueLessThanOrEqual { get; set; }
		public int? EstoqueGreaterThanOrEqual { get; set; }
		public int? PrecoEqual { get; set; }
		public int? PrecoNotEqual { get; set; }
		public int[]? PrecoContains { get; set; }
		public int[]? PrecoNotContains { get; set; }
		public int? PrecoSince { get; set; }
		public int? PrecoUntil { get; set; }
		public int? PrecoLessThan { get; set; }
		public int? PrecoGreaterThan { get; set; }
		public int? PrecoLessThanOrEqual { get; set; }
		public int? PrecoGreaterThanOrEqual { get; set; }
		public int? CategoriaIdEqual { get; set; }
		public int? CategoriaIdNotEqual { get; set; }
		public int[]? CategoriaIdContains { get; set; }
		public int[]? CategoriaIdNotContains { get; set; }
		public int? CategoriaIdSince { get; set; }
		public int? CategoriaIdUntil { get; set; }
		public int? CategoriaIdLessThan { get; set; }
		public int? CategoriaIdGreaterThan { get; set; }
		public int? CategoriaIdLessThanOrEqual { get; set; }
		public int? CategoriaIdGreaterThanOrEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class MarketPlaceAggSettingsQueryModel : BaseQueryModel<MarketPlaceAggSettings> {
        public override Expression<Func<MarketPlaceAggSettings, bool>> GetFilter() => MarketPlaceAggSettingsFilters.GetFilters(this, IsOrSpecification==true);
		public int? UserIdEqual { get; set; }
		public int? UserIdNotEqual { get; set; }
		public int[]? UserIdContains { get; set; }
		public int[]? UserIdNotContains { get; set; }
		public int? UserIdSince { get; set; }
		public int? UserIdUntil { get; set; }
		public int? UserIdLessThan { get; set; }
		public int? UserIdGreaterThan { get; set; }
		public int? UserIdLessThanOrEqual { get; set; }
		public int? UserIdGreaterThanOrEqual { get; set; }
		public bool? AutoSaveSettingsEnabledEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class CarrinhoQueryModel : BaseQueryModel<Carrinho> {
        public override Expression<Func<Carrinho, bool>> GetFilter() => CarrinhoFilters.GetFilters(this, IsOrSpecification==true);
		public int? ProdutoIdEqual { get; set; }
		public int? ProdutoIdNotEqual { get; set; }
		public int[]? ProdutoIdContains { get; set; }
		public int[]? ProdutoIdNotContains { get; set; }
		public int? ProdutoIdSince { get; set; }
		public int? ProdutoIdUntil { get; set; }
		public int? ProdutoIdLessThan { get; set; }
		public int? ProdutoIdGreaterThan { get; set; }
		public int? ProdutoIdLessThanOrEqual { get; set; }
		public int? ProdutoIdGreaterThanOrEqual { get; set; }
		public int? UsuarioIdEqual { get; set; }
		public int? UsuarioIdNotEqual { get; set; }
		public int[]? UsuarioIdContains { get; set; }
		public int[]? UsuarioIdNotContains { get; set; }
		public int? UsuarioIdSince { get; set; }
		public int? UsuarioIdUntil { get; set; }
		public int? UsuarioIdLessThan { get; set; }
		public int? UsuarioIdGreaterThan { get; set; }
		public int? UsuarioIdLessThanOrEqual { get; set; }
		public int? UsuarioIdGreaterThanOrEqual { get; set; }
		public int? PagamentoEqual { get; set; }
		public int? PagamentoNotEqual { get; set; }
		public int[]? PagamentoContains { get; set; }
		public int[]? PagamentoNotContains { get; set; }
		public int? PagamentoSince { get; set; }
		public int? PagamentoUntil { get; set; }
		public int? PagamentoLessThan { get; set; }
		public int? PagamentoGreaterThan { get; set; }
		public int? PagamentoLessThanOrEqual { get; set; }
		public int? PagamentoGreaterThanOrEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class CategoriaprodutoQueryModel : BaseQueryModel<Categoriaproduto> {
        public override Expression<Func<Categoriaproduto, bool>> GetFilter() => CategoriaprodutoFilters.GetFilters(this, IsOrSpecification==true);
		public string? NomeEqual { get; set; }
		public string? NomeNotEqual { get; set; }
		public string? NomeContains { get; set; }
		public string? NomeStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
